logo1 = 'C:/Users/Sohamdeep/OneDrive/Desktop/Term Python Project 2022/Assets/img1.png'
logo2 = 'C:/Users/Sohamdeep/OneDrive/Desktop/Term Python Project 2022/Assets/img2.png'
def themes():
    thm = [('#ffeee7', '#141312', logo1),('#48d9a2', '#2e2d3f', logo2)]
    return thm
def fonts():
    fnts =  ['Space Mono', 'Avenir LT Std 45 Book','Kiwi Maru']
    return fnts
def story():
    stories = [("The Midnight Hour", "Disclaimer \
some parts in this story may be found disturbing and creepy. Listen to it at your own risk. hi my name is lawliet and today i will be talking to u about my paranormal night that literally knocked the life out of me. so this had happened when corona had just started creating chaos around the world and lockdown was imposed everywhere. At that time we had online classes and so we got this one assignment to record ourselves skipping for 1 week for a minute. So I did the skipping for the first six days and thought that I would record the last day of skipping at midnight, when everyone was asleep. I don't know why I thought of that. probably the worst mistake in my life. so when everyone in my house had gone to sleep i went to my living room to record the last day of skipping. I had finished recording and sat down to edit because I wanted to show myself as a perfect person who does not make any mistakes in anything. So while I was editing the video in the living room I heard some footsteps. I thought that it would be my mom or dad or my brother. so i waited for that person to walk in the living room to see why the light was left on. I waited and waited, and no one came. I thought that I was hearing things and went back to editing. A few minutes later I again heard footsteps. but this one felt a bit weird because it kind of sounded the same as the first one which was the sound of someone walking barefoot. but then I realized that none of my family members walk barefoot in the house .They all wear slippers almost all the time. The footsteps stopped. I went outside the living room to check who it was. I found no one. I again went back to editing but this time I was keeping an eye on the living room hallway. again the footsteps came ,this time i bolted out to check who it was. I could find no one. all my family members were sleeping. so whose footsteps it was the whole time. I quickly finished off with the editing and decided to head to sleep. While I was a few inches away from my room I heard a whisper. I could not quite understand it so I did not pay much attention to it mainly because I was also scared to death. I thought that I was safe since nothing else happened after I went to bed. or so I thought. I woke up in the middle of the night because I heard something.like something breaking. When I wake up, I am not able to move my body. you guessed it, it was sleep paralysis. using my peripheral vision i tried to see why my chest felt so heavy as if someone was sitting on it. I will never be able to forget what I saw. I got a glimpse of massive legs crushing my chest. I was finding it hard to breathe. Then suddenly when I was again able to move my body.......I saw a shadow go behind me and when I tried to turn to see where it went, i felt heavy breathing on my neck as if someone was right behind me. I turned back and no one was there. mind you that all of this happened that same night. to this day that paranormal experience keeps bothering me."),
        ("Double Embarassment", "Hello my name is brian and today i will talk about  two stories : how i almost drowned in a pool and how my teacher outsmarted us all students. \
One of my greatest weaknesses as a human being is that I absolutely 100 percent cannot swim to save my own life. In fact, that's what drowning is. I mean, I could be in the kiddie pool and I'd still be like, 'Help, please! I'm dying!' and some grown up be like 'oh my god! Call 911!' and a small Kid in the pool was like ' Ugh. What an insolent child this lad is.'  So, flash back to primary school brian; innocent, sense of joy intact, hadn't drowned yet- where I was at a party over at my rich friend's house. Now I knew he was rich because he had a pool. And if that isn't a sign that you're making some serious dosh, then I don't know what is. I was swimming around the edges of the pool because you know, the water is terrifying. But seeing all my friends in the middle of the pool,enjoying the water, having a blast,I felt like I was missing out. So in order to join them and get over the fear of swimming, I took a step forward into the unknown and… And as soon as I went under, I thought I could probably just kick up from the bottom of the pool to get back to the surface. But then suddenly one of the kids' pool mats was over my head. Like it was almost a little too quick- (Kid In Pool be like ‘ Guys, we got him! Get on the mat, quick!’ )So yeah, I started to drown. And as I was drowning, it was finally time for my critical problem solving. I assembled a quick team of my brain and me. So this was my plan A  ’  Okay, so let's lift the mat.’and my brain goes like’ Wait, that wouldn't work. You're just a child, you're not that strong to lift that entire mat off. I mean, who would think of such a stupid hair brain dumb idea? ‘’Well, all right, plan B:swim to the side and get out.’and for that too my brain goes like’ We don't know how to swim.’ So plan C it is: death. Yep. That sounds pretty reasonable. I like that. I've been waiting to die to be honest. Thankfully, I was quickly rescued by my rich friend's mom who then gave me a little swimming donut to keep me alive. She then recommended swimming lessons to my mom, but of course I didn't really care. I was just hyped that I got my own swim ring. And the coolest thing about it was that it was in the shape of a sheep because of course it would. It's New Zealand.\
 So before I begin with my second story I should probably say : \
 DISCLAIMER \
The stunts performed in this story have been done by professionals. please do not try to imitate or copy any of the stunts shown. So now with that out of the way, let's continue. So we had made this one group of failures in 11 standard who had decided to cheat in the upcoming exams because the papers were starting to become a little too difficult.(mainly because we wasted the entire 6 months of the year doing nothing). So to give us the idea there was one guy in our group who had a master plan. He said “the paper will be of 3 hours from 10 am to 1 pm. At 12:05 I will cough. Then at that moment you all start moving your benches. The teacher will think it is an earthquake and send all the students outside. At that time we will take our answer sheets as well and the exam is canceled!!’ We all thought that the plan was a master plan and we went ahead with it the next day. All went according to plan. At 12:05 we all started to move our benches when he coughed. Only two problems. He never told us when to stop... and... neither did the teacher tell us to go out. Instead he kept staring at students and slowly the benches stopped moving. The kid in the last bench shouts that ‘the earthquake came in a wave’ to which the teacher replies ‘my dear son, next time when the earthquake come do remind the teacher to move the teachers table as well."),
        ("The Locked Door", "The key glistened as the afternoon sun kissed it lightly. It seemed to taunt me, whispering that this was what I had been waiting for, refusing to go unnoticed any longer. My sister, Mary, sat next to me. Her eyes, too, were fixed on the golden object that offered so many answers. The air around us seemed to change as expectation hung in the air. Was today the day we’d finally get to go into Dad’s locked door?\
For as long as I can remember, the door was forbidden. In fact, just a stare in the general direction of the room would be enough to make Dad flushed and furious, rambling on about how children needed to respect boundaries. We never questioned it when we were young, for the young simply trusted and accepted. However, as the years passed, Mary and I spent nights discussing the forbidden room in our home. He always carried the key on his person, as if it was painful just not to be near it. Today was an exception, a beautiful, welcome exception. He had stormed out the door so quickly that the key was left behind. The question that now arose was whether we would use it. \
Dad was well-known in our little neck of the woods, well-known, yes, but not liked. The phrase ‘mad scientist’ was frequently used to describe my father. Once, I also heard someone describing Dr. Gerhard Bucksman as evil. Eccentric, yes, cold, absolutely, irrational, agreed, but not evil, surely. That was a label that our father didn’t deserve, so I hoped. \
Mary’s gaze, like mine, remained uninterrupted, as if the key had cast a spell on us both. “Are we really going to do it?” I asked after more time had passed. My voice sounded small and weak. “Dad would be so mad if he knew,” Mary said, and then a big smile appeared on her face. She clapped her hands and shouted, “Let’s do it! Who knows if we’ll ever get this opportunity!” Oh, how I love my sister. “OK, grab it,” I said, matching her enthusiasm now. “No, you,” she replied. Although we were curious, we weren’t as brave as we’d like to think we were. It seemed childish for two teenage girls to play paper, scissors, stone, but we did what we had to reach an agreement. It was me who lost, and so, I leaned over and grabbed the key. It felt cold and small in my hand.\
The door seemed larger as we approached it as if it was trying to keep us out with its immense size. Our eyes met, and we stared at each other, wondering what we’d find behind the locked door. Mary gave me a slight nod, encouraging me to go ahead. The key slipped into the lock with ease making a slight click sound. I took a deep breath, turned the key, and opened the door.\
The room was dusty, smelly, and unwelcoming. The stench in the air consumed my nostrils, making my eyes water. I heard Mary cough, although she seemed far away. Other than the smell and dust, the room seemed rather ordinary. Stacks of paper lay on the desk to the side of the room, documents that contained scientific scribbles that only those who shared my father’s mind would understand. In the far corner stood jars of dark liquid with unknown membranes floating in them. I had seen those in the laboratory at school the year before. Mary had gotten detention after taking all the frogs outside and setting them free. “Someone had to save those poor unfortunate creatures,” she had told Mrs. Gluttenheim an hour later. The memory made me smile—Mary, sweet, goodhearted Mary. \
Machinery that was unfamiliar decorated the walls. I turned around to take in the entire room and let out a sigh. I was overcome with a mixture of relief and disappointment. At least now we knew what Dad had hidden in his precious locked room, a whole lot of nothing. I turned to find my way back to the door, best to lock up before Dad returned. I felt a hand on my shoulder and jumped. Relieved, I realized that Mary had reached out to me. I giggled. Mary didn’t respond; she merely stood staring ahead of her. There in the shadows, lay a hidden room. \
The light flickered on harshly, lighting up the room instantly while making a buzzing noise. There were machines here, too, each dedicated to its purpose, pumping, recording, extracting. A bright green liquid moved through long and curly tubes, which led to a hand, a beautiful, human hand. My eyes scanned over the image in front of me, trying to understand what I was seeing. We stood silently, wondering whether what they said about Dad was true. Here, on the table, in the small hidden room, behind his locked door, lay a woman. She was asleep, a kind release of her current reality, I supposed. \
“Why would he do this?” Mary’s question interrupted my thoughts. I thought to myself that men had reasons for being cruel when it came to women but remained silent. I reached out and touched her foot. She felt cold. A small piece of paper was stuck to the table. The words initium finis were written on it in red ink. Yet another scribble that made no sense. My eyes ran over the woman’s body once more, and I jumped when my eyes met hers. Her eyes were the only part of her that didn’t seem human, more prominent, rounder, and entirely black. My heart bled for this creature, tied to a steel table in a hidden room for who knows how long. I heard soft sobs, Mary. Bless her gentle heart.\
“Why would he do this?” she said again softly through the sobs. I didn’t respond because I knew she wasn’t ready to hear what I thought. The cold truth was that our father was playing God, but he lacked empathy. Creating life was one thing, but containing it like this was a sin much worse in my mind. My fingers ran over the small piece of paper that lay at her feet once more, and then we did what we had to. We set her free.\ She moved quickly past us, and she was out of our lives, although I knew we’d never forget her. The machines had slowed down; some had stopped completely, lost in purpose. I’m not sure how long we stood there, taking it all in, trying to make sense of what we had seen. Then, finally, my father’s screams behind us dragged us back to our reality. “What have you done, you idiotic girls!” he shouted with his hands in his hair. He looked like he wanted to cry but left the room. We heard the wheels of his car spin in the driveway. My sister was still sobbing quietly. She, too, would never be the same again.\
With cups of warm tea in our hands, we sat in front of the laptop. Mary smiled, and I returned her smile and typed the words I so longed to know the meaning of. If we had known that would be the last smile we shared, we would have prolonged it, treasured it, held on to it. But, instead, on the screen, the words read the beginning of the end.")
    ]
    return stories
